 /** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  output: 'standalone',
  trailingSlash: false,
  images: {
    unoptimized: true,
  },
  env: {
    PUBLIC_AI_SERVICE_SOCKET_ENDPOINT: process.env.PUBLIC_AI_SERVICE_SOCKET_ENDPOINT,
    PUBLIC_AI_SERVICE_API_ENDPOINT: process.env.PUBLIC_AI_SERVICE_API_ENDPOINT,
    PUBLIC_CTRL_SERVICE_API_ENDPOINT: process.env.PUBLIC_CTRL_SERVICE_API_ENDPOINT,
    DEBUG_ENV: process.env.DEBUG_ENV,
  },
  transpilePackages: [
    "@ant-design",
    "@rc-component",
    "antd",
    "rc-cascader",
    "rc-checkbox",
    "rc-collapse",
    "rc-dialog",
    "rc-drawer",
    "rc-dropdown",
    "rc-field-form",
    "rc-image",
    "rc-input",
    "rc-input-number",
    "rc-mentions",
    "rc-menu",
    "rc-motion",
    "rc-notification",
    "rc-pagination",
    "rc-picker",
    "rc-progress",
    "rc-rate",
    "rc-resize-observer",
    "rc-segmented",
    "rc-select",
    "rc-slider",
    "rc-steps",
    "rc-switch",
    "rc-table",
    "rc-tabs",
    "rc-textarea",
    "rc-tooltip",
    "rc-tree",
    "rc-tree-select",
    "rc-upload",
    "rc-util",
    '@annotorious/react'
  ],
};

module.exports = nextConfig;
